extensionName: hello-world
hostAddress: 0.0.0.0
hostPort: 4532
opensearchAddress: xxxx
opensearchPort: 9200
#ssl.transport.enabled: true
#ssl.transport.pemcert_filepath: certs/extension-01.pem
#ssl.transport.pemkey_filepath: certs/extension-01-key.pem
#ssl.transport.pemtrustedcas_filepath: certs/root-ca.pem
#ssl.transport.enforce_hostname_verification: false
#path.home: <path/to/extension>
